import type { Product, PublicSettings } from "./types";

// Local sample data used for PREVIEW MODE only — when Supabase env vars aren't
// set yet, the customer UI renders against this so the design is fully browsable
// without a database. Mirrors supabase/migrations/0002_seed.sql.

const NOW = "2026-07-03T00:00:00.000Z";

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Zesty Loaded Nachos",
    description: "Crispy nachos, melted cheddar, jalapeños & fresh pico de gallo.",
    price: 120,
    original_price: null,
    stock: 25,
    available: true,
    category: "hot",
    image_url:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAF3pqfWEAgmjSPNXMaiuux-JsBfrrsAIWiH6cJCDNinBG4qVC2jWi3RR-cFPtnyJCMZrmXZU14-3m4OuWlaMGOdzJkAlf8cRxN9P5MwR6Xp1m5GqWh8HH-j8v1LJUsh_obaz5zvSbRXQz338vepMebesBd0BxM3GhmkF7fRUYBblJfzCn5aj_CtL869ySEw08DFbzHBHtoJxqeKwhid1nzfx1wE3aQXvQhZ46qnr4yIaML6Q-bjs0qMlH_EYVRqG1rQks0JpiKaUPI",
    featured: true,
    created_at: NOW,
  },
  {
    id: 2,
    name: "Blue Bolt Energy",
    description: "Ice-cold energy drink to power your all-nighter.",
    price: 60,
    original_price: null,
    stock: 40,
    available: true,
    category: "drinks",
    image_url:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDPvZRGQnGgimoaBS16OIr_0rCQ2RSPh8lv8vsmeMto5LYE5BUciAJYl7H9rBGXwQiOxazXBSucqwfDKHCNE2c0d0XrOowg_DZGfWpnN_hv5sFZi8bY2Sj86ft6Lp9TUHBY6cj1ZrEdQC3d7uDaZOYklvfkDR5D3PrxFp_o8SFdyHp2tkkLCFTxvnJ00yfDagM69qQCyOE_WsMcteSASixIwuKstnz2E5GKFgpcwGi1F9-TiYYDwQKNCk_gCXUuqyGmWmMQ4M8NsPLH",
    featured: true,
    created_at: NOW,
  },
  {
    id: 3,
    name: "Dark Sea Salt Bar",
    description: "Artisanal dark chocolate with sea salt crystals.",
    price: 50,
    original_price: null,
    stock: 30,
    available: true,
    category: "sweets",
    image_url:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuA4fELWd7sskR1k5PFWKzGneAGiTatV_7JEpIM3ZU_yZwJ1f2UeHU5DUS48XtMpnho4DHEaFLQNxKHgsax3h8jlON9QO7v5C4KX66mZ7xUyUzhR3iMISiWg-9VPYR0i2aQ8_VRADWF2pAtzIvjBn3Zj0PRvjs751P4_CuYuIl065fRwNCPRtpqwwB2CIT4kKXjAIbJLBxbdN3_RQj7TY9X6dx88pbQWQX9VZ70OyaVeMsC4DRcoy6hKJL5TOq_up1jszpGFfVuFAyGd",
    featured: true,
    created_at: NOW,
  },
  {
    id: 4,
    name: "Glazed Donuts (2-for-1)",
    description: "Warm glazed donuts with sprinkles. Perfect for study groups!",
    price: 40,
    original_price: 80,
    stock: 20,
    available: true,
    category: "sweets",
    image_url:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCgDMbS6dFbi7nqF3LQ1OjJFtNNptPyR1eJ8JAnVbCxRMxZMpvd7mLjtAsqTJHlzBOpVXuahdOrsEaVamtwBwgFhAvHQ3RyC2Uc6Mzk2iF2KO7e18SSQZloOm-yLaloUl3z5BtOVSWqObUZfJ7Ikw1niFfdOAhuhvOT5-pTgklk7iWZZAbyHVzdOsju9CGLDQIKaXBg0MERRC8lV0L0uiM9cycDFqvrhFNNiOa0p-eUEPoU0VQSuEBSTYPNBUDiLBK_ovW-hPAAOr3a",
    featured: false,
    created_at: NOW,
  },
  {
    id: 5,
    name: "Mixed Berry Cup",
    description: "Organic blueberries, raspberries & strawberries.",
    price: 90,
    original_price: null,
    stock: 15,
    available: true,
    category: "healthy",
    image_url:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBys7xaTNamV6V6Ntdw3QxWa0wc-578JOAEqJqB61s7K1TTA4YmJF6fny-PJkVTOH8Gv2gg_RgtrT55ib96WSgoytZLpG3TFy8leLWHopdfsJOUQrN6dLuI_HULUqwaKJA4REP-nIOZiEc1dKqXYSxSgLmaNjwEX2Me_N10fEZMZBUcS0w1YfV9GX9gZT5m1Oa3LTEQaLhxoLNXsobjBr8ekkRdBtHTqOc2G0Gx4Aceyjhc32P-Qb81e8SnOXXiUJ4VitDp0eL5i-AE",
    featured: false,
    created_at: NOW,
  },
  {
    id: 6,
    name: "Protein Nut Mix",
    description: "Roasted salted almonds & cashews. High-protein boost.",
    price: 75,
    original_price: null,
    stock: 18,
    available: true,
    category: "healthy",
    image_url:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDzWqiSDYWB-CPtI1fdrPiugVqp69jfXKU2FygGFdcFKnalUTMDj9N20q7FdUBitHx_qSzOxrYFZcMPBD03kTK_8vD7e0RYfu09z9im0lSsVMIJtO2Xd58XeyYel_gpILJztKOSY4u33Ts2PVv3ABX-ycQGpNAzzeTvJDmbrnM9jtBfRO6wTcOGgk9VvvjtWEp4lNzwo2ALNVYC_eoWNt_3_WzU9x6zqlclsZ8T5L9BaORNwTCek0uGDKIbDPoyDUiwh9Rzx6sYuLXw",
    featured: false,
    created_at: NOW,
  },
  {
    id: 7,
    name: "Sea Salt Kale Chips",
    description: "Crispy baked kale chips with a hint of sea salt.",
    price: 50,
    original_price: null,
    stock: 22,
    available: true,
    category: "chips",
    image_url:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDksydjmvWNPk4Rtu98zikAOefgcLTHt2VEStRZNC1dPn-6yuLbf3Vq1s2X7DCdhnrRZN3vSjgnSCU-h74Akw17kDXOoZo0ZNogZNAWLKl3WRTYLH8q2ulS1OMDMH7Pm25Vzb20wkI7QvFIVD9xFML1nXtOzHniMBAYY8OLHI8qmzcdyW0nDZaJJL7HGcpxf_7iAqLlJOjqCoOWA49ZXgC280u0t5JsSk_5-F31AwkKTzN2_GrTzWx-hbHOV86Ngd-hgEXyG6OpmBzr",
    featured: false,
    created_at: NOW,
  },
  {
    id: 8,
    name: "Masala Potato Chips",
    description: "Classic tangy masala crunch.",
    price: 30,
    original_price: null,
    stock: 50,
    available: true,
    category: "chips",
    image_url: null,
    featured: false,
    created_at: NOW,
  },
  {
    id: 9,
    name: "Cold Coffee",
    description: "Chilled creamy cold coffee.",
    price: 70,
    original_price: null,
    stock: 28,
    available: true,
    category: "drinks",
    image_url: null,
    featured: false,
    created_at: NOW,
  },
  {
    id: 10,
    name: "Veg Samosa (2 pcs)",
    description: "Hot, flaky samosas with spiced potato filling.",
    price: 40,
    original_price: null,
    stock: 35,
    available: true,
    category: "hot",
    image_url: null,
    featured: false,
    created_at: NOW,
  },
  {
    id: 11,
    name: "Chocolate Muffin",
    description: "Rich double-chocolate muffin.",
    price: 55,
    original_price: null,
    stock: 3,
    available: true,
    category: "sweets",
    image_url: null,
    featured: false,
    created_at: NOW,
  },
];

export const DEMO_SETTINGS: PublicSettings = {
  id: "demo",
  shop_name: "TMP at NU",
  upi_id: "tmpatnu@upi",
  qr_code_url: null,
  tagline: "Get your favorites delivered in minutes.",
  enable_quick_pay: true,
  orders_enabled: true,
  created_at: NOW,
  updated_at: NOW,
};
