/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      // ---- Ported verbatim from the Figma design's tailwind.config (Material 3 tokens) ----
      colors: {
        "surface-tint": "#a04100",
        "on-error": "#ffffff",
        "surface-container-high": "#e8e8e8",
        error: "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#ffdf94",
        "primary-container": "#ff6b00",
        secondary: "#765b00",
        "on-surface": "#1a1c1c",
        "secondary-fixed-dim": "#f5bf00",
        "on-secondary": "#ffffff",
        "on-background": "#1a1c1c",
        "outline-variant": "#e2bfb0",
        "surface-container-highest": "#e2e2e2",
        "error-container": "#ffdad6",
        "surface-container": "#eeeeee",
        "surface-variant": "#e2e2e2",
        "on-surface-variant": "#5a4136",
        "surface-dim": "#dadada",
        background: "#f9f9f9",
        "on-primary-container": "#572000",
        "on-secondary-fixed": "#251a00",
        primary: "#a04100",
        "tertiary-fixed-dim": "#c8c6c5",
        "secondary-container": "#ffc703",
        "on-primary": "#ffffff",
        "on-secondary-container": "#6e5400",
        "inverse-primary": "#ffb693",
        "on-tertiary-container": "#313131",
        "on-secondary-fixed-variant": "#594400",
        outline: "#8e7164",
        tertiary: "#5f5e5e",
        "on-tertiary-fixed": "#1c1b1b",
        "surface-container-low": "#f3f3f3",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f1f1f1",
        "tertiary-container": "#9a9898",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#351000",
        "on-tertiary-fixed-variant": "#474746",
        "surface-bright": "#f9f9f9",
        "primary-fixed-dim": "#ffb693",
        "on-primary-fixed-variant": "#7a3000",
        "tertiary-fixed": "#e5e2e1",
        "on-tertiary": "#ffffff",
        surface: "#f9f9f9",
        "primary-fixed": "#ffdbcc",
        // convenience aliases used by success/warning/info states in this app
        success: "#0f9d58",
        "success-container": "#c8f0d8",
        warning: "#f5bf00",
        info: "#0891b2",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        lg: "24px",
        "container-margin": "16px",
        xs: "4px",
        gutter: "12px",
        base: "4px",
        md: "16px",
        sm: "8px",
        xl: "32px",
      },
      fontFamily: {
        "label-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg-mobile": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-md": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
      keyframes: {
        "bounce-subtle": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-4px)" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in-right": {
          "0%": { opacity: "0", transform: "translateX(24px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
      },
      animation: {
        "bounce-subtle": "bounce-subtle 3s infinite ease-in-out",
        "fade-in": "fade-in 0.3s ease-out",
        "slide-in-right": "slide-in-right 0.3s ease-out",
      },
    },
  },
  plugins: [],
};
